### ISSUE TITLE
[navigation] pop all stack (clear stack), then navigating to new `NavRoot`

### ISSUE THREAD

**Issue by hoc081098** [freeletics/khonshu#582]
Hi, I have a use case
- When launching my app, I will check whether the user is logged in or not
  - if logged in -> `startRoute` is `LoginScreenRoute` (a `NavRoot`) (1).
  - otherwise ->  `startRoute` is `HomeScreenRoute` (a `NavRoot`) (2).
- In the login screen, after the successful login, my expected behavior is popping all stack (clear stack), then navigating to `HomeScreenRoute` (3). After that, the back stack should contain only an entry, which is `HomeScreenRoute`, and the user cannot navigate to back `LoginScreenRoute`.

```
Back stack:
LOGGED IN:        [ HomeScreenRoute  ] (1)
NOT LOGGED IN:    [ LoginScreenRoute ] (2)
SUCCESSFUL LOGIN: [ HomeScreenRoute. ] (3)
```

Currently, I implement this by changing the `startRoute` to reset the `NavGraph` of the `NavController` (related to #580).
I have also used `NavEventNavigator.resetToRoot(HomeScreenRoute)` but I could navigate to back the `LoginScreenRoute`.

Is there a better approach to achieve this behavior, maybe using the `NavEventNavigator`? Many thanks 🙏

**Comment by gabrielittner** [comment]
We currently don't have anything for this. `resetToRoot` is mostly meant for going back to the current root at the end of a flow or when you have bottom tabs and reselect the current tab. The main reason why we don't have something is that when I tried something like this before there were weird behaviors by Androidx navigation when the start destination wasn't on the backstack anymore. However that was a long time ago and might not be the case anymore or it also could have been Fragment related. We're currently starting the process of moving our main app to compose navigation and I was planning to revisit this topic afterwards because it's easier if we only need to consider compose.
